export const MERCHANT_CONTEXT_TAGS: Record<string, string> = {
  "ファミリーマート": "Convenience Store",
  "セブン-イレブン": "Convenience Store",
  "ローソン": "Convenience Store",
  "ローソン (QP)": "Convenience Store",
  "ローソン 北海道": "Convenience Store · Hokkaido",
  "デイリーヤマザキ": "Convenience Store",
  "セイコーマート": "Convenience Store",
  "セイコーマート ルスツ": "Convenience Store · Rusutsu",
  "セイコーマート 真狩": "Convenience Store · Makkari",
  "ワイズマート": "Supermarket",
  "ワイズマート (QP)": "Supermarket",
  "ハナマサプラス": "Wholesale Grocery",
  "ハナマサプラス 根岸店": "Wholesale Grocery · Negishi",
  "マイバスケット": "Discount Grocery",
  "ドラッグセイムス": "Drug Store",
  "ドラッグセイムス 三ノ輪店": "Drug Store · Minowa",
  "パパス 三ノ輪店": "Bakery · Minowa",
  "ダイソー": "100¥ Store",
  "マクドナルド": "McDonald's",
  "マクドナルド 三ノ輪店": "McDonald's · Minowa",
  "ドミノピザ": "Domino's Pizza",
  "一蘭": "Ramen · Ichiran",
  "一蘭 アトレ上野": "Ramen · Ichiran Ueno",
  "一蘭 渋谷スペイン坂": "Ramen · Ichiran Shibuya",
  "シェイクシャック": "Shake Shack",
  "シェイクシャック 六本木": "Shake Shack · Roppongi",
  "ヤマト運輸": "Yamato Delivery",
  "東京ガス": "Tokyo Gas",
  "ジャパン電力 (電気代)": "Japan Power · Electricity",
  "水道料金": "Water Utility",
  "NTT東日本": "NTT East · Internet",
  "NTT東日本 光コラボ": "NTT East · Internet",
  "NTT東日本 光コラボ (Internet)": "NTT East · Internet",
  "楽天モバイル": "Rakuten Mobile",
  "povo利用料金": "povo Mobile",
  "au電話利用料": "au Mobile",
  "GOアプリ": "GO Taxi",
  "GOアプリ プレミアム": "GO Taxi · Premium",
  "GOアプリ 乗車料金": "GO Taxi · Fare",
  "S.RIDE タクシー 台東": "S.RIDE Taxi · Taito",
  "ウーバーイーツ": "Uber Eats",
  "JALプラザ": "JAL",
  "JALプラザ 羽田空港": "JAL · Haneda Airport",
  "日本航空": "Japan Airlines",
  "日本航空 国際航空券": "Japan Airlines · International",
  "JR東日本 えきねっと": "JR East · Train Tickets",
  "ケイセイスカイライナー": "Keisei Skyliner",
  "ルスツリゾート": "Rusutsu Resort · Ski",
  "キロロリゾート": "Kiroro Resort · Ski",
  "苗場スキー場": "Naeba Ski Resort",
  "苗場スキー場 リフト券": "Naeba · Lift Ticket",
  "フジテンリゾート スキー場": "Fujiten Ski Resort",
  "ニセコ駅前温泉 きらのゆ": "Niseko Onsen · Kiranoyu",
  "真狩BASE (スキー)": "Makkari Base · Ski",
  "ニッポンレンタカー": "Nippon Rent-a-Car",
  "ニッポンレンタカー (リボ)": "Nippon Rent-a-Car",
  "パークハイアット東京": "Park Hyatt Tokyo",
  "パークハイアット東京 (リボ)": "Park Hyatt Tokyo",
  "品川プリンスホテル": "Shinagawa Prince Hotel",
  "ザ・ミレニアルズ渋谷 (Square)": "Millennials Shibuya",
  "Hostel Bedgasm": "Hostel · Bedgasm",
  "Hana 1 Cafe (Square) キロロ": "Hana 1 Cafe · Kiroro",
  "申告所得税": "Income Tax Payment",
  "申告所得税及復興特別所得税": "Income Tax · Reconstruction",
  "羽田空港ラウンジ": "Haneda Airport Lounge",
  "新千歳空港 ターミナル": "New Chitose Airport",
  "六本木ヒルズ": "Roppongi Hills",
  "T・ジョイ PRINCE 品川": "T-Joy Cinema · Shinagawa",
  "グランドシネマサンシャイン": "Grand Cinema Sunshine",
  "グランドシネマサンシャイン (QP)": "Grand Cinema Sunshine",
  "TK NIGHT CLUB": "TK Night Club",
  "VENT": "Vent · Bar",
  "VENT (Square) バー": "Vent · Bar",
  "TRAFFIC (Square) バー": "Traffic · Bar",
  "ホブソンズ西麻布": "Hobson's · Nishiazabu",
  "パセラ 渋谷店": "Pasela · Shibuya",
  "チョップス渋谷店": "Chops · Shibuya",
  "リューズ ヌードルバー": "Ryus Noodle Bar",
  "日高屋 六本木店": "Hidakaya · Roppongi",
  "ローンパイン": "Lone Pine",
  "ANTHOLOGY": "Anthology",
  "ビストロウエハラ": "Bistro Uehara",
  "ウーム": "Womb",
  "レストランアラジン": "Restaurant Aladdin",
  "FONDA MEXICANA 銀座": "Fonda Mexicana · Ginza",
  "鈴木酒販 小売部": "Suzuki Sake Shop",
  "クオカード購入": "QUO Card Purchase",
  "コカコーラ 自販機": "Coca-Cola · Vending",
  "エキュートエディション有楽町": "Ecute Edition · Yurakucho",
  "東京倶楽部ビルディング霞ダイニング": "Tokyo Club Bldg · Kasumi Dining",
  "日本橋室町三井タワー ミッドタウンクリニック": "Midtown Clinic · Nihonbashi",
  "FIT PLACE (ジム)": "FIT PLACE · Gym",
  "PRECIOUS LAB": "Precious Lab",
  "HANAZONO EDGE": "Hanazono Edge",
  "THE GREY ROOM/NFC": "The Grey Room",
  "WAmazing": "WAmazing",
  "instabase": "Instabase",
  "ジェイトリップ (スキーツアー)": "J-Trip · Ski Tour",
  "WOODBERRY COFFEE (Square)": "Woodberry Coffee",
  "NCコインロッカー キロロリゾート": "Coin Locker · Kiroro",
  "Amazon Marketplace (JCB分割1回目)": "Amazon · JCB Installment 1/2",
  "AMAZON.CO.JP (分割2回目)": "Amazon · Installment 2/2",
  "Paidy あと払い (Amazon)": "Paidy · Amazon",
  "AGODA ホテル (India)": "Agoda · India Hotel",
  "AIR INDIA WEB (国内線)": "Air India · Domestic",
  "JAPAN AIRLINES NEW DELHI (リボ)": "JAL · New Delhi",
  "GMR AIRPORTS LTD DELHI": "Delhi Airport · GMR",
  "HALIMA KEBAB BIRYANI": "Halima Kebab · Biryani",
  "PYU*ZOMATO LIMITED (India)": "Zomato · India",
  "PYU*AMAZON SELLER SERVICE (India)": "Amazon · India",
  "RAZ*BLINKIT (India)": "Blinkit · India",
  "RAZ*ZOMATO ONLINE ORDER (India)": "Zomato · India",
  "ZOMATO (India)": "Zomato · India",
  "SOCIAL ONLINE PAYMENTS LI (India)": "Social Online · India",
  "CTRLPOTATO (Prague) ソフトウェア": "CtrlPotato · Software",
  "TIMEMORE (UK) コーヒー器具": "Timemore · Coffee Gear",
  "SP US.GETCARV.COM (スキー器具)": "Carv · Ski Gear",
  "NAMECHEAP.COM (ドメイン)": "Namecheap · Domain",
  "GOOGLE CLOUD": "Google Cloud",
  "PATREON MEMBERSHIP": "Patreon",
  "CLAUDE.AI SUBSCRIPTION (Anthropic)": "Claude.ai · Anthropic",
  "SURFSHARK VPN": "Surfshark VPN",
  "SURFSHARK VPN 返金": "Surfshark VPN · Refund",
  "Amazonプライム会費": "Amazon Prime",
  "FISCHER TUNING BASE (リボ)": "Fischer Tuning Base",
  "CRAFTALE (リボ)": "Craftale",
  "THE RESTAURANT (リボ)": "The Restaurant",
  "イオン北海道 (リボ)": "Aeon · Hokkaido",
  "加森観光 WEBチケット (リボ)": "Kamori Kanko · Web Ticket",
  "バボラ ピュアドライブ (メルペイ)": "Babolat · Pure Drive",
  "楽天ペイ 博多串焼 かめや": "Rakuten Pay · Hakata Kushiyaki",
  "グーテ ル ブレイリヤ": "Gout et Bleurija · Bakery",
  "NOSTRA PIZZA (Square)": "Nostra Pizza",
  "SQ*株式会社manmal (Square)": "Manmal Co.",
  "インド料理ニュープラシッダ": "Indian · New Prasidha",
  "家賃 カ)トラストアドバイザーズ": "Rent · Trust Advisors",
  "家賃 (Trust Advisors)": "Rent · Trust Advisors",
  "振込 オザワ アサミ": "Transfer · Ozawa Asami",
  "振込 タジマ チサト": "Transfer · Tajima Chisato",
  "振込 ピーエムシー (副業)": "Transfer · PMC (side job)",
  "振込 TIGERCAMPUSPT": "Transfer · TigerCampus PT",
  "振込 ワイズ (Wise送金)": "Transfer · Wise",
  "振込手数料": "Transfer Fee",
  "給与 ロバートウォルターズ": "Salary · Robert Walters",
  "キャッシュバック ポイント交換 (SMBC)": "SMBC · Cashback Points",
  "フリー (freee)": "freee",
  "SMBC リボ弁済金": "SMBC · Ribo Payment",
  "JCB リボ弁済金": "JCB · Ribo Payment",
  "セゾン リボ弁済金": "Saison · Ribo Payment",
  "Paidy Apple月払い": "Paidy · Apple Monthly",
};

export function getMerchantContextTag(merchant: string): string | null {
  return MERCHANT_CONTEXT_TAGS[merchant] ?? null;
}
